-- Content library: master content separated from where it is placed.
--
-- Generated by drizzle-kit from api/src/db/schema.ts, then hand-patched for two
-- reasons worth knowing before regenerating:
--
--  * drizzle-kit emits `ALTER TABLE Section ADD contentItemId text REFERENCES
--    content_items(id)` and DROPS the `ON DELETE set null` ACTION that schema.ts
--    declares. Without the action the foreign key still refuses a placement pointing at
--    a row that does not exist, but deleting a library item would FAIL on the foreign key
--    instead of unlinking the placement -- the opposite of the SET NULL that schema.ts and
--    the table comment promise. SQLite accepts a REFERENCES-bearing ADD COLUMN as long as
--    the column defaults to NULL, which it does, so the fix is to re-add the action by
--    hand. If you regenerate this file, check that `ON DELETE set null` survived; the
--    REFERENCES clause itself does come through.
--
--    (Verified against drizzle-kit 0.31.11: a freshly added FK column is emitted as
--    `text REFERENCES <table>(<col>)` with no ON DELETE clause.)
--
--  * `content_items` is keyed by userId, not by resume. A content item is the master
--    copy of one achievement or skill group and may be placed in several resume
--    variants; keying it to a resume would make that impossible and would turn the
--    library into a per-resume copy.
--
-- No backfill here. Existing sections keep working with a NULL contentItemId (the
-- column is nullable on purpose), and api/src/trpc/procedures/content.ts backfills
-- them idempotently. Doing it in SQL would need JSON functions whose availability on
-- D1 is not something to bet a migration on.

CREATE TABLE `content_items` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`payload` text NOT NULL,
	`archivedAt` integer,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `content_items_user_archived_idx` ON `content_items` (`userId`,`archivedAt`);--> statement-breakpoint
CREATE INDEX `content_items_user_type_idx` ON `content_items` (`userId`,`type`);--> statement-breakpoint
ALTER TABLE `Section` ADD `contentItemId` text REFERENCES content_items(id) ON DELETE set null;--> statement-breakpoint
CREATE INDEX `Section_contentItemId_idx` ON `Section` (`contentItemId`);