-- Content library: master content separated from where it is placed.
--
-- Generated by drizzle-kit from api/src/db/schema.ts, then hand-patched for two
-- reasons worth knowing before regenerating:
--
--  * drizzle-kit emits `ALTER TABLE Section ADD contentItemId text` and DROPS the
--    REFERENCES clause. Without it the ON DELETE SET NULL that schema.ts declares is
--    not enforced by the database, so archiving or removing an item would leave
--    dangling placements instead of unlinking them. SQLite accepts a
--    REFERENCES-bearing ADD COLUMN as long as the column defaults to NULL, which it
--    does. If you regenerate this file, check that clause survived.
--
--  * `content_items` is keyed by userId, not by resume. A content item is the master
--    copy of one achievement or skill group and may be placed in several resume
--    variants; keying it to a resume would make that impossible and would turn the
--    library into a per-resume copy.
--
-- No backfill here. Existing sections keep working with a NULL contentItemId (the
-- column is nullable on purpose), and api/src/trpc/procedures/content.ts backfills
-- them idempotently. Doing it in SQL would need JSON functions whose availability on
-- D1 is not something to bet a migration on.

CREATE TABLE `content_items` (
	`id` text PRIMARY KEY NOT NULL,
	`userId` text NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`payload` text NOT NULL,
	`archivedAt` integer,
	`createdAt` integer NOT NULL,
	`updatedAt` integer NOT NULL,
	FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `content_items_user_archived_idx` ON `content_items` (`userId`,`archivedAt`);--> statement-breakpoint
CREATE INDEX `content_items_user_type_idx` ON `content_items` (`userId`,`type`);--> statement-breakpoint
ALTER TABLE `Section` ADD `contentItemId` text REFERENCES content_items(id) ON DELETE set null;--> statement-breakpoint
CREATE INDEX `Section_contentItemId_idx` ON `Section` (`contentItemId`);